development:
  adapter: MongoDB
  host: localhost
  database: "#myapp-development"

test:
  adapter: MongoDB
  host: localhost
  database: "#myapp-development"

production:
  uri: mongodb://admin:123456@linus.mongohq.com:10042/app13390540